// AUTO-GENERATED by scripts/gen-registry.mjs — do not edit.
import type React from 'react';
import Shot0, { compositionConfig as cfg0 } from './compositions/BrandProof';
import Shot1, { compositionConfig as cfg1 } from './compositions/FabricDetail';
import Shot2, { compositionConfig as cfg2 } from './compositions/HeroReveal';
import Shot3, { compositionConfig as cfg3 } from './compositions/PriceReveal';
import Shot4, { compositionConfig as cfg4 } from './compositions/SetReveal';

export const shots: { Comp: React.FC; config: any }[] = [
  { Comp: Shot0 as React.FC, config: cfg0 },
  { Comp: Shot1 as React.FC, config: cfg1 },
  { Comp: Shot2 as React.FC, config: cfg2 },
  { Comp: Shot3 as React.FC, config: cfg3 },
  { Comp: Shot4 as React.FC, config: cfg4 },
];
