// AUTO-GENERATED by scripts/gen-registry.mjs — do not edit.
import type React from 'react';
import Shot0, { compositionConfig as cfg0 } from './compositions/BentoGallery';
import Shot1, { compositionConfig as cfg1 } from './compositions/BentoReel';
import Shot2, { compositionConfig as cfg2 } from './compositions/BrandProof';
import Shot3, { compositionConfig as cfg3 } from './compositions/CardConverge';
import Shot4, { compositionConfig as cfg4 } from './compositions/CinematicReveal';
import Shot5, { compositionConfig as cfg5 } from './compositions/DetailFocus';
import Shot6, { compositionConfig as cfg6 } from './compositions/DynamicGrid';
import Shot7, { compositionConfig as cfg7 } from './compositions/FabricDetail';
import Shot8, { compositionConfig as cfg8 } from './compositions/HeroReveal';
import Shot9, { compositionConfig as cfg9 } from './compositions/LifestyleFrame';
import Shot10, { compositionConfig as cfg10 } from './compositions/PriceReveal';
import Shot11, { compositionConfig as cfg11 } from './compositions/ProductSplit';
import Shot12, { compositionConfig as cfg12 } from './compositions/PromoHighlight';
import Shot13, { compositionConfig as cfg13 } from './compositions/SetReveal';
import Shot14, { compositionConfig as cfg14 } from './compositions/ShaderDissolve';
import Shot15, { compositionConfig as cfg15 } from './compositions/ShowcaseCard';

export const shots: { Comp: React.FC; config: any }[] = [
  { Comp: Shot0 as React.FC, config: cfg0 },
  { Comp: Shot1 as React.FC, config: cfg1 },
  { Comp: Shot2 as React.FC, config: cfg2 },
  { Comp: Shot3 as React.FC, config: cfg3 },
  { Comp: Shot4 as React.FC, config: cfg4 },
  { Comp: Shot5 as React.FC, config: cfg5 },
  { Comp: Shot6 as React.FC, config: cfg6 },
  { Comp: Shot7 as React.FC, config: cfg7 },
  { Comp: Shot8 as React.FC, config: cfg8 },
  { Comp: Shot9 as React.FC, config: cfg9 },
  { Comp: Shot10 as React.FC, config: cfg10 },
  { Comp: Shot11 as React.FC, config: cfg11 },
  { Comp: Shot12 as React.FC, config: cfg12 },
  { Comp: Shot13 as React.FC, config: cfg13 },
  { Comp: Shot14 as React.FC, config: cfg14 },
  { Comp: Shot15 as React.FC, config: cfg15 },
];
