// AUTO-GENERATED by scripts/gen-registry.mjs — do not edit.
import type React from 'react';
import Shot0, { compositionConfig as cfg0 } from './compositions/BrandProof';

export const shots: { Comp: React.FC; config: any }[] = [
  { Comp: Shot0 as React.FC, config: cfg0 },
];
